"""
A grasshopper python scrip that can bake a object generated by grasshopper
credit: https://discourse.mcneel.com/t/baking-grasshopper-project/74516/6

input:
    - obj: type hint has to be changed into "GeometryBase"

"""

import scriptcontext as sc
import System.Drawing as sd
import Rhino.DocObjects as rd
import Rhino.Geometry as rg
import Rhino

attr = rd.ObjectAttributes()

sc.doc = Rhino.RhinoDoc.ActiveDoc

type = obj.ObjectType
if type == rd.ObjectType.Point:
    sc.doc.Objects.AddPoint(obj.Location, attr)
elif type == rd.ObjectType.Curve:
    sc.doc.Objects.AddCurve(obj, attr)
elif type == rd.ObjectType.Surface:
    sc.doc.Objects.AddSurface(obj, attr)
elif type == rd.ObjectType.Brep:
    sc.doc.Objects.AddBrep(obj, attr)
elif type == rd.ObjectType.Mesh:
    sc.doc.Objects.AddMesh(obj, attr)
else:
    print "object type " + str(type) + " is not baked"